[colors.bright]
black = "#7f7f7f"
blue = "#1b64e4"
cyan = "#00ffff"
green = "#00ff00"
magenta = "#ff00ff"
red = "#ff0000"
white = "#ffffff"
yellow = "#ffff00"

[colors.normal]
black = "#000000"
blue = "#6f93ff"
cyan = "#00cdcd"
green = "#00cd00"
magenta = "#cd00cd"
red = "#cd0000"
white = "#e5e5e5"
yellow = "#cdcd00"

[colors.primary]
background = "#000000"
foreground = "#e5e5e5"

[cursor]
blink_interval = 500

[cursor.style]
blinking = "Always"
shape = "Underline"

[font]
size = 14.0

[font.normal]
family = "Ubuntu Mono"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Super|Shift"

[window]
opacity = 0.8

[window.dimensions]
columns = 80
lines = 25
